# Generated by Django 3.2 on 2021-06-25 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofftype',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
