# Generated by Django 3.2 on 2021-07-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20210703_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeoffrequest',
            name='paid',
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='payment_status',
            field=models.CharField(choices=[('FP', 'Full Pay'), ('HP', 'Half Pay'), ('NP', 'No Pay')], default='FP', max_length=2),
        ),
    ]
