# Generated by Django 3.2 on 2021-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_auto_20210718_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customholiday',
            name='from_date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='customholiday',
            name='to_date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='to_date',
            field=models.DateField(),
        ),
    ]
