# Generated by Django 3.2 on 2021-08-31 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_country'),
        ('leaves', '0005_auto_20210811_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
