# Generated by Django 3.2 on 2021-08-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_organization'),
        ('organization', '0004_alter_organization_country'),
        ('leaves', '0006_timeoffrequest_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customholiday',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='timeoffrequest',
            unique_together={('from_date', 'to_date', 'time_off_type', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='timeofftype',
            unique_together={('name', 'organization')},
        ),
    ]
