# Generated by Django 3.2 on 2021-07-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_populate_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.country'),
        ),
    ]
