# Generated by Django 3.2 on 2021-09-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='slack_workspace_id',
        ),
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_team_id', models.CharField(max_length=250, null=True)),
                ('slack_team_name', models.CharField(max_length=250, null=True)),
                ('bot_user_id', models.CharField(max_length=250, null=True)),
                ('app_id', models.CharField(max_length=250, null=True)),
                ('access_token', models.CharField(max_length=1000, null=True)),
                ('channel', models.CharField(max_length=250, null=True)),
                ('channel_id', models.CharField(max_length=250, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
