# Generated by Django 3.2 on 2021-09-02 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210901_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackintegration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackintegration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
