# Generated by Django 3.2 on 2021-09-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20210902_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slack_integrated',
            field=models.BooleanField(default=False),
        ),
    ]
